version: '3'

services:
  frontend:
    container_name: mospan_pro_frontend
    restart: always
    build: /Users/ugo/projects/mospan_pro_frontend
    ports:
      - '8080:8080'
    env_file:
      - /Users/ugo/projects/mospan_pro_frontend/.env
    links:
      - backend
  backend:
    container_name: mospan_pro_backend
    restart: always
    build: .
    ports:
      - '8081:8081'
    env_file:
      - .env
    links:
      - database
  database:
    container_name: mospan_pro_database
    image: mariadb:10.4
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env

volumes:
  db-data: