version: '3'

services:
  backend:
    container_name: mospan_pro_backend
    restart: always
    build: .
    ports:
      - '8081:8081'
    env_file:
      - .env
    links:
      - database
  database:
    container_name: mospan_pro_database
    image: mariadb:10.4
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env

volumes:
  db-data: